services:
  app:
    build: .
    container_name: 9C-Docker-container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db-9c.crcmik6a8cf4.ap-northeast-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USERNAME: ParkMinseo
      DB_PASSWORD: qkralstjDB1!
      DB_NAME: NineCDataBase
    restart: always
volumes:
  db-data:
